name: Deploy to Amazon Public ECR

on:
  push:
    branches:
      - main  # Trigger only when pushing to the main branch

jobs:
  deploy:
    name: Build and Push to Public ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Log in to Amazon Public ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build and Tag Docker Image
        run: |
          docker build -t public.ecr.aws/m8i1w4q6/myrecipebook:latest -t public.ecr.aws/m8i1w4q6/myrecipebook:${{ env.SHORT_SHA }} .

      - name: Push Docker Image to Public ECR
        run: |
          docker push public.ecr.aws/m8i1w4q6/myrecipebook:latest
          docker push public.ecr.aws/m8i1w4q6/myrecipebook:${{ env.SHORT_SHA }}

      - name: Verify Pushed Images
        run: |
          echo "Pushed images to ECR:"
          echo " - public.ecr.aws/m8i1w4q6/myrecipebook:latest"
          echo " - public.ecr.aws/m8i1w4q6/myrecipebook:${{ env.SHORT_SHA }}"
